default_platform(:ios)

desc "Create app on Developer portal and App Store Connect"
lane :create_app do
  create_app_online # produce
end

platform :ios do
  desc "Sync signing"
  lane :sign do
    
  end

  desc "Build binary"
  lane :build do
    sign
  end

  desc "Release"
  lane :release do
    build
  end
end

