default_platform(:ios)

desc "Create app on Developer portal and App Store Connect"
lane :create_app do
  create_app_online # produce
end

platform :ios do
  before_all do
    Dotenv.load ".env.ios"
  end

  desc "Sync signing"
  lane :sign do
    sync_code_signing # match
    
    # Manually updating code signing setting
    mapping = Actions.lane_context[
      SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING
    ]
    # This will modify the Xcode project and we will do a git reset at the end to revert
    update_code_signing_settings(
      profile_name: mapping[ENV['MATCH_APP_IDENTIFIER']]
    )
  end

  desc "Build binary"
  lane :build do
    sign
    build_ios_app
  end

  desc "Release"
  lane :release do
    build
  end
end

